### ISSUE TITLE
Can't create tables on mariadb

### ISSUE THREAD

**Issue by Alexre** [AlessioDP/LastLoginAPI#13]
I can't create the required tables to make the plugin work, here is the specific error:

`java.lang.RuntimeException: com.alessiodp.lastloginapi.libs.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.SQLException: Index column size too large. The maximum column size is 767 bytes. [statement:"CREATE TABLE IF NOT EXISTS `lastloginapi_players` ( `uuid` VARCHAR(255) NOT NULL PRIMARY KEY, `name` VARCHAR(255) DEFAULT '', `lastLogin` INTEGER DEFAULT 0 NOT NULL, `lastLogout` INTEGER DEFAULT 0 NOT NULL )", arguments:{positional:{}, named:{}, finder:[]}]
`
Using mariadb 10.1.44-MariaDB-0+deb9u1 Debian 9.11

Already tried to enable innodb_large_prefix

**Comment by AlessioDP** [comment]
Well, MariaDB is not really implemented. For sure I will do it with upcoming updates, it wasn't my priority because with mysql driver it was working fine.

You should try to google the error and see if you can fix it by editing the database, I know some servers that use mariadb don't have this problem, strange :S

I will mark this as enhancement for mariadb support.
